/*-------------------------------------------------------------------------------
	S.A.M Framework — the built-in Hunter's Workbench.
	See sam_workbench.hpp for the design + the no-op rule.
-------------------------------------------------------------------------------*/

#include "sam_workbench.hpp"
#include "sam_items.hpp"
#include "sam_recipes.hpp"
#include "sam_logger.hpp"

#include <fstream>
#include <cstdio>
#include <sys/stat.h>
#ifdef _WIN32
#	include <direct.h>
#endif

#if defined(__has_include) && __has_include("items.hpp")
#	define SAM_WORKBENCH_HAVE_BARONY 1
#	include "items.hpp"
#	include "files.hpp"   // outputdir
#endif

// The generated byte arrays. This is the ONLY translation unit that includes them.
#include "sam_workbench_art.h"

static const char* MOD = "WORKBENCH";

namespace
{
	// Where the embedded assets land. Deliberately NOT under mods/: the main menu lists
	// every mods/ subdirectory as a loadable local mod, and the bench's art is not a mod.
	const char* kAssetSubdir = "sam_builtin/workbench";

	std::string joinPath(const std::string& dir, const std::string& file)
	{
		if ( dir.empty() ) { return file; }
		if ( file.empty() ) { return dir; }
		const char last = dir[dir.size() - 1];
		if ( last == '/' || last == '\\' ) { return dir + file; }
		return dir + "/" + file;
	}

	bool sizeOnDisk(const std::string& path, long long& out)
	{
		struct stat st;
		if ( stat(path.c_str(), &st) != 0 ) { return false; }
		out = (long long)st.st_size;
		return true;
	}

	void makeDirs(const std::string& path)
	{
		// Create each component in turn. The parent (outputdir) always exists already.
		for ( size_t i = 0; i < path.size(); ++i )
		{
			if ( path[i] != '/' && path[i] != '\\' ) { continue; }
			const std::string part = path.substr(0, i);
			if ( part.empty() || part == "." ) { continue; }
#ifdef _WIN32
			_mkdir(part.c_str());
#else
			mkdir(part.c_str(), 0755);
#endif
		}
#ifdef _WIN32
		_mkdir(path.c_str());
#else
		mkdir(path.c_str(), 0755);
#endif
	}

	bool s_installed = false;
}


std::string SAMWorkbench::assetDir()
{
#ifdef SAM_WORKBENCH_HAVE_BARONY
	return joinPath(std::string(outputdir), kAssetSubdir);
#else
	return std::string(kAssetSubdir);
#endif
}

namespace
{
	// Write out anything missing or the wrong size. Returns how many assets are present
	// and correct afterwards.
	int extractAssets()
	{
		const std::string dir = SAMWorkbench::assetDir();
		makeDirs(dir);

		int ok = 0;
		for ( int i = 0; i < SAM_WORKBENCH_ASSET_COUNT; ++i )
		{
			const SAMWorkbenchAsset& a = SAM_WORKBENCH_ASSETS[i];
			const std::string path = joinPath(dir, a.file);

			// Compare against the embedded length rather than merely testing existence, so
			// a build that ships new art actually replaces the old file on disk.
			long long have = 0;
			if ( sizeOnDisk(path, have) && have == (long long)a.len ) { ++ok; continue; }

			std::ofstream f(path.c_str(), std::ios::binary | std::ios::trunc);
			if ( !f.is_open() )
			{
				SAM_WARN(MOD, "Could not write '" + path + "' (read-only install?) — the workbench "
					"falls back to the vanilla tinkering art for this piece.");
				continue;
			}
			f.write((const char*)a.data, (std::streamsize)a.len);
			f.close();

			// A PARTIAL write is worse than none: a truncated PNG still passes an existence
			// check, and a failed image load is cached forever, so that panel piece would be
			// permanently invisible. Delete it so the vanilla fallback takes over instead.
			long long wrote = 0;
			if ( !f.good() || !sizeOnDisk(path, wrote) || wrote != (long long)a.len )
			{
				std::remove(path.c_str());
				SAM_WARN(MOD, "Short write for '" + std::string(a.file) + "' — removed it so the "
					"vanilla art is used rather than a broken image.");
				continue;
			}
			++ok;
		}
		return ok;
	}
}

void SAMWorkbench::install()
{
#ifdef SAM_WORKBENCH_HAVE_BARONY
	if ( s_installed ) { return; }

	const int ok = extractAssets();
	SAM_INFO(MOD, "Hunter's Workbench assets ready (" + std::to_string(ok) + "/"
		+ std::to_string(SAM_WORKBENCH_ASSET_COUNT) + ").");

	SAMItemDef def;
	def.id              = "sam:hunters_workbench";
	def.modNamespace    = "sam";
	// Real filesystem dir: getKitUiPath and the icon loader both stat the path, so this
	// must be an OS path, not a PhysFS logical one.
	def.modPath         = assetDir();
	def.nameIdentified   = "hunter's workbench";
	def.nameUnidentified = "hunter's workbench";
	def.description = "A portable bench for working bone, hide and sinew.\nUse it to craft.";
	def.category    = "TOOL";
	def.weight      = 15;
	def.goldValue   = 120;
	def.level       = -1;   // never rolls as random loot

	// The models resolve through PhysFS, where outputdir is mounted at the root, so the
	// logical path is the subdir + filename (no outputdir prefix).
	def.model    = std::string(kAssetSubdir) + "/Hunters_Toolkit.vox";
	def.modelFp  = std::string(kAssetSubdir) + "/Hunters_Toolkit_FP.vox";
	// The 2D inventory sprite, resolved against modPath (a real filesystem dir), so this
	// one is a bare filename rather than a PhysFS path like the models above.
	def.icon     = "Hunters_Toolkit.png";

	// Panel skin. Values are bare filenames because modPath is already the asset dir.
	// Any role whose file failed to extract simply resolves empty and keeps vanilla art.
	static const struct { const char* role; const char* file; } kSkin[] = {
		{ "base",               "Hunting_Construct_Base.png" },
		{ "drawer",             "Hunting_Drawer.png" },
		{ "name_plate",         "Hunter_LabelName_2Row.png" },
		{ "cost_backing",       "Hunter_CostBacking.png" },
		{ "scrap_backing",      "Hunter_ScrapBacking.png" },
		{ "item_surround",      "Hunter_ItemBGSurround.png" },
		{ "prompt_left",        "Hunter_PromptCoverLeft.png" },
		{ "prompt_right",       "Hunter_PromptCoverRight.png" },
		{ "arrow_left",         "Hunter_Button_ArrowL.png" },
		{ "arrow_right",        "Hunter_Button_ArrowR.png" },
		{ "close",              "Hunter_Button_X.png" },
		{ "close_high",         "Hunter_Button_XHigh.png" },
		{ "close_press",        "Hunter_Button_XPress.png" },
		{ "filter_left",        "Hunter_Filter_Left.png" },
		{ "filter_left_high",   "Hunter_Filter_LeftHigh.png" },
		{ "filter_center",      "Hunter_Filter_Center.png" },
		{ "filter_center_high", "Hunter_Filter_CenterHigh.png" },
		{ "filter_right",       "Hunter_Filter_Right.png" },
		{ "filter_right_high",  "Hunter_Filter_RightHigh.png" },
	};
	for ( const auto& s : kSkin ) { def.kitUi[s.role] = s.file; }

	if ( !SAMItems::registerBuiltinAt(SAM_ITEM_HUNTERS_WORKBENCH, def) )
	{
		SAM_ERROR(MOD, "Could not register the Hunter's Workbench — it will not be available.");
		return;
	}

	// Bind it as a kit independently of recipes, so it opens the moment a mod puts it in a
	// class loadout, even before that mod adds anything craftable to it.
	SAMRecipes::registerBuiltinKit(SAM_ITEM_HUNTERS_WORKBENCH);

	s_installed = true;
	SAM_INFO(MOD, "Hunter's Workbench registered as item id "
		+ std::to_string(SAM_ITEM_HUNTERS_WORKBENCH) + " [sam:hunters_workbench].");
#endif
}

void SAMWorkbench::clear()
{
	s_installed = false;
}
